### ISSUE TITLE
A special test case for picoCTF2019 flags_shop (general) question

### ISSUE THREAD

**Issue by Peiqi-Hu** [Dvd848/CTFs#7]
Hey there, I was working on the flag shop question and I found your writeup for that question. I tried 3333333 for the amount which worked successfully. But when I tried the number 2386093 and 2386094, which gave a negative total cost as expected but the account balance was still negative. I wasn't sure it is because of the program itself, or because of some hidden rule for the extreme cases. 
I got 2386093 by dividing 2^31 by 900 since 2^31 is the negative max for 32-bit int. 
However, 2386095 works perfectly. 

Thanks a lot. 

![picflagshop94](https://user-images.githubusercontent.com/26306522/89700579-3f630180-d8fd-11ea-8e92-3d075a5bd29a.JPG)
![picoflagshop](https://user-images.githubusercontent.com/26306522/89700584-438f1f00-d8fd-11ea-9cb9-fc7be2fba950.JPG)
![picoflagshop95](https://user-images.githubusercontent.com/26306522/89700587-4a1d9680-d8fd-11ea-8af9-884bb1083d44.JPG)

**Comment by Dvd848** [comment]
Hi,

It's not enough to overflow the `total_cost`, you also need to take into consideration the subtraction involving `account_balance`.
If we extract just the logic which is directly related to the calculation, we get:

```c
  int total_cost = 0;
  int account_balance = 1100;

  printf("\nNumber of flags: %d\n", number_flags);
  total_cost = 900 * number_flags;
  printf("\nThe final cost is: %d\n", total_cost);
  account_balance = account_balance - total_cost;
  printf("\nYour current balance after transaction: %d\n\n", account_balance);
```

Now, for `number_flags = 2386093`, we get `total_cost = -2147483596`. 
This means that `account_balance - total_cost` is:
```python
>>> 1100 - (-2147483596)
2147484696L
>>> bin(1100 - (-2147483596))
'0b10000000000000000000010000011000'
>>> ((1100 - (-2147483596)) & (1 << 31)) != 0
True
```

Since the result still has BIT31 set, it is interpreted as a negative number (this is how Two's Complement works).

Same goes for `number_flags = 2386094`:
```python
>>> 1100 - (-2147482696)
2147483796L
>>> bin(1100 - (-2147482696))
'0b10000000000000000000000010010100'
>>> ((1100 - (-2147482696)) & (1 << 31)) != 0
True
```

Only when `number_flags = 2386095`, the result of the calculation has BIT31 cleared, resulting in a positive number:
````python
>>> 1100 - (-2147481796)
2147482896
>>> bin(1100 - (-2147481796))
'0b1111111111111111111110100010000'
>>> ((1100 - (-2147481796)) & (1 << 31)) != 0
False
```

**Comment by Peiqi-Hu** [comment]
Thank you very much! Now it makes sense to me.
